### ISSUE TITLE
Not picking up prettier.config.js

### ISSUE THREAD

**Issue by boojum** [neoclide/coc-prettier#54]
Official `prettier` docs mention few config files ([here](https://prettier.io/docs/en/configuration.html)), one of them is `prettier.config.js`. Are you planning to make `coc-prettier` pick it up?

**Comment by liamcaccetta** [comment]
+1, in my project doesn't work any prettier config, I don't know why.

**Comment by fabiomcosta** [comment]
"prettier.config.js" has always been one of the supported config names as seen at https://github.com/neoclide/coc-prettier/blob/1fbfe34dfce455111e3eae939fc8a37d2fd1ec42/src/configCacheHandler.ts#L15

I thing I would do to help others debug your issue is paste your `CocConfig` here, as well as your `prettier.config.js`

**Comment by boojum** [comment]
Apologies for the untimely reply, I took some time off screens and networks.

You are absolutely right `prettier.config.js` works just fine. I had a typo in my config (_facepalm_)...
