### ISSUE TITLE
option   "prettier.printWidth": 80 in  cocConfig files is not respected

### ISSUE THREAD

**Issue by grimgort** [neoclide/coc-prettier#59]
Hello,
When I run the following command, the line size of my markdown and json files exceeds 80 characters. 
:CocCommand prettier.formatFile

Thank you !!

**Comment by callumacrae** [comment]
I'm also having this same issue - it's formatting everything but the line widths.

**Comment by samuelbran** [comment]
I had this issue, the problem was a misconfiguration in my `.prettierrc` file, I was using `"tralingComma": false` which is not a valid option, so I changed it to `"trailingComma": "none"` and the `printWidth` started to work again.

**Comment by fabiomcosta** [comment]
Hello folks I had this issue as well and the issue is that you need to set "proseWrap" to "always".
https://prettier.io/docs/en/options.html#prose-wrap
Make sure you have the latest version of Prettier as this option has changes overtime.

Extra info: https://github.com/prettier/prettier/issues/6488

**Comment by grimgort** [comment]
it s work thanks !!
