### ISSUE TITLE
Add support for prettier-standard

### ISSUE THREAD

**Issue by gbrlsnchs** [neoclide/coc-prettier#9]
Please, would you consider adding support for [`prettier-standard`](https://github.com/sheerun/prettier-standard)? I can have it with `ALE` but would rather use `coc.nvim` instead.

**Comment by chemzqm** [comment]
It can't, because it doesn't provide API https://github.com/sheerun/prettier-standard/blob/master/src/index.js

**Comment by JackCA** [comment]
Stumbling upon this since I was hoping to replace ale's fixing functionality with this. Somehow ale supports it ([per the prettier-standard docs](https://github.com/sheerun/prettier-standard#vim))

**Comment by chemzqm** [comment]
It can't, unless prettier-standard can be used as prettier extension which I think it should instead of fork prettier.

**Comment by JackCA** [comment]
@chemzqm I agree that I wish prettier-standard wasn't a fork, but their [docs even mention that they support the same API](https://github.com/sheerun/prettier-standard#api). Maybe I'm missing something there.

On a separate note:

> It's not designed to replace your other plugin like ale.

what territory of ALE does CoC not cover or intend to cover?

I've just replaced ALE's linting with coc-eslint, so the only reason I'm using ALE is because it supports prettier-standard.

**Comment by jtrussell** [comment]
Could a possible workaround involve lettings folks provide a path to the prettier executable (related #36), or specify the prettier module name (e.g. https://github.com/neoclide/coc-prettier/blob/master/src/utils.ts#L29)?

**Comment by chemzqm** [comment]
@jtrussell PR welcome.

**Comment by jtrussell** [comment]
Cool - I'll give it a shot :).
